/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/*
* MainFrame.java
*
* Created on 2 ñ³÷ 2012, 9:40:50
*/

/**
*
* @author errorist
*/
public class MainFrame extends javax.swing.JFrame {

   /** Creates new form MainFrame */
   public MainFrame() {
	   initComponents();
   }

   /** This method is called from within the constructor to
	* initialize the form.
	* WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the Form Editor.
	*/
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

	   jScrollPane1 = new javax.swing.JScrollPane();
	   jList1 = new javax.swing.JList();
	   jButton1 = new javax.swing.JButton();
	   jButton2 = new javax.swing.JButton();
	   jLabel1 = new javax.swing.JLabel();
	   jTextField1 = new javax.swing.JTextField();
	   jLabel2 = new javax.swing.JLabel();
	   jLabel3 = new javax.swing.JLabel();
	   jScrollPane2 = new javax.swing.JScrollPane();
	   jTextArea1 = new javax.swing.JTextArea();
	   jLabel4 = new javax.swing.JLabel();
	   jSpinner1 = new javax.swing.JSpinner();
	   jScrollPane3 = new javax.swing.JScrollPane();
	   jTable1 = new javax.swing.JTable();
	   jLabel5 = new javax.swing.JLabel();
	   jButton3 = new javax.swing.JButton();
	   jButton4 = new javax.swing.JButton();
	   jButton5 = new javax.swing.JButton();
	   jTextField2 = new javax.swing.JTextField();

	   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	   setTitle("mooCoder Task Manager");

	   jScrollPane1.setName("jScrollPane1"); // NOI18N

	   jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
	   jList1.setToolTipText("Select task to edit");
	   jList1.setName("jList1"); // NOI18N
	   jScrollPane1.setViewportView(jList1);

	   jButton1.setText("Add");
	   jButton1.setToolTipText("Add a new, blank task");
	   jButton1.setName("jButton1"); // NOI18N

	   jButton2.setText("Remove");
	   jButton2.setToolTipText("Remove selected task");
	   jButton2.setName("jButton2"); // NOI18N

	   jLabel1.setText("Tasks:");
	   jLabel1.setName("jLabel1"); // NOI18N

	   jTextField1.setToolTipText("Choose a title for this task. NOTE: no HTML is allowed!");
	   jTextField1.setName("jTextField1"); // NOI18N

	   jLabel2.setText("Title:");
	   jLabel2.setToolTipText("");
	   jLabel2.setName("jLabel2"); // NOI18N

	   jLabel3.setText("Description:");
	   jLabel3.setToolTipText("");
	   jLabel3.setName("jLabel3"); // NOI18N

	   jScrollPane2.setName("jScrollPane2"); // NOI18N

	   jTextArea1.setColumns(20);
	   jTextArea1.setRows(5);
	   jTextArea1.setToolTipText("Choose a description for this task. NOTE: this field allows HTML");
	   jTextArea1.setName("jTextArea1"); // NOI18N
	   jScrollPane2.setViewportView(jTextArea1);

	   jLabel4.setText("Points per test:");
	   jLabel4.setName("jLabel4"); // NOI18N

	   jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
	   jSpinner1.setToolTipText("This one defines how much points could user get solving it correctly");
	   jSpinner1.setName("jSpinner1"); // NOI18N

	   jScrollPane3.setName("jScrollPane3"); // NOI18N

	   jTable1.setModel(new javax.swing.table.DefaultTableModel(
		   (Object [][]) [
			   [null, null, null]
		   ],
		   (String []) [
			   "Input", "Correct Output", "Time limit (ms)"
		   ]
	   ) {
		   Class[] types = (Class []) [
			   java.lang.String.class, java.lang.String.class, java.lang.Integer.class
		   ];

		   public Class getColumnClass(int columnIndex) {
			   return types [columnIndex];
		   }
	   });
	   jTable1.setToolTipText("This table contains tests assigned to this task. You can simply edit the values within the cells. Note to press \"Save\" when you are done editing the task or its tests");
	   jTable1.setName("jTable1"); // NOI18N
	   jScrollPane3.setViewportView(jTable1);

	   jLabel5.setText("Tests:");
	   jLabel5.setName("jLabel5"); // NOI18N

	   jButton3.setText("Add");
	   jButton3.setToolTipText("Create a new, blank test");
	   jButton3.setName("jButton3"); // NOI18N

	   jButton4.setText("Remove");
	   jButton4.setToolTipText("Remove this test");
	   jButton4.setName("jButton4"); // NOI18N

	   jButton5.setText("Save");
	   jButton5.setToolTipText("Store changes in DB");
	   jButton5.setName("jButton5"); // NOI18N

	   jTextField2.setToolTipText("Quick search");
	   jTextField2.setName("jTextField2"); // NOI18N

	   javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	   getContentPane().setLayout(layout);
	   layout.setHorizontalGroup(
		   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		   .addGroup(layout.createSequentialGroup()
			   .addContainerGap()
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				   .addGroup(layout.createSequentialGroup()
					   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
						   .addComponent(jLabel1)
						   .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
				   .addGroup(layout.createSequentialGroup()
					   .addComponent(jButton1)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jButton2)
					   .addGap(60, 60, 60)))
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					   .addComponent(jButton3)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jButton4)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
					   .addComponent(jButton5))
				   .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
				   .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
				   .addComponent(jLabel2)
				   .addComponent(jLabel4)
				   .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
				   .addComponent(jLabel5)
				   .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
				   .addComponent(jLabel3))
			   .addContainerGap())
	   );
	   layout.setVerticalGroup(
		   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
			   .addContainerGap()
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				   .addComponent(jLabel1)
				   .addComponent(jLabel2))
			   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
			   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				   .addGroup(layout.createSequentialGroup()
					   .addComponent(jLabel3)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jLabel4)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					   .addGap(7, 7, 7)
					   .addComponent(jLabel5)
					   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					   .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
				   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
			   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				   .addComponent(jButton5)
				   .addComponent(jButton1)
				   .addComponent(jButton2)
				   .addComponent(jButton3)
				   .addComponent(jButton4))
			   .addContainerGap())
	   );

	   pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
   * @param args the command line arguments
   */
   public static void main(args) {
	   java.awt.EventQueue.invokeLater(new Runnable() {
		   public void run() {
			   new MainFrame().setVisible(true);
		   }
	   });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JList jList1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JSpinner jSpinner1;
   private javax.swing.JTable jTable1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   // End of variables declaration//GEN-END:variables

}
